services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env
    ports:
      - "3001:3000"
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    external: true

volumes:
  grafana_data:
