services:
  litellm:
      image: ghcr.io/berriai/litellm:main-latest
      container_name: litellm
      ports:
        - "4000:4000"
      env_file:
        - .env
      volumes:
        - ./litellm_config.yaml:/app/config.yaml
      command: ["--config", "/app/config.yaml"]
      restart: unless-stopped
